### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Uevo001** [diphons/D8G_Kernel_oxygen#18]
Greetings. 
I am not good at building a kernel. So, when I want to build the kernel successfully, I have no idea what parameters I need to add. Need I add the commands such as ` NM=llvm-nm OBJDUMP=llvm-objdump STRIP=llvm-strip`?
Or I wonder whether there is a build script? 
Could you offer my some suggestions?

**Comment by diphons** [comment]
Try this:

dir_out=out
make -j$(nproc --all) O=$dir_out \\
                      ARCH=arm64 \\
                      CC=clang \\
                      LLVM=1 \\
                      LLVM_IAS=1 \\
                      CROSS_COMPILE=aarch64-linux-gnu- \\
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi- \\
                      NM=llvm-nm \\
                      OBJCOPY=llvm-objcopy \\
                      OBJDUMP=llvm-objdump \\
                      STRIP=llvm-strip \\
                      Image.gz \\
                      dtbo.img

**Comment by Uevo001** [comment]
Should I use Google Clang `r498229b`? I get an error: 

``` UPD     include/generated/asm-offsets.h
  CALL    ../scripts/checksyscalls.sh
  LDS     arch/arm64/kernel/vdso/vdso.lds
  CC      arch/arm64/kernel/vdso/vgettimeofday.o
  AS      arch/arm64/kernel/vdso/note.o
  HOSTCC  scripts/dtc/util.o
/usr/bin/as: unrecognized option '-EL'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../scripts/Makefile.build:438: arch/arm64/kernel/vdso/note.o] Error 1
make[1]: *** [arch/arm64/Makefile:225: vdso_prepare] Error 2
make[1]: *** Waiting for unfinished jobs....
